// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getServiceRoleKey() {
  const k = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SERVICE_ROLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lY3RqZG5ndnJxbnh3aG53ZnJ0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mjg5MTM1NCwiZXhwIjoyMDg4NDY3MzU0fQ.tTGgSv0_6aSRjekzCFB7VlA0jC-vUn8FECt21PiDPwk";
  return k.replace(/^["']|["']$/g, "").trim();
}

function getSupabaseUrl() {
  const u = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.VITE_SUPABASE_URL || "https://oectjdngvrqnxwhnwfrt.supabase.co";
  return u.replace(/^["']|["']$/g, "").trim();
}

export function getMissingSupabaseAdminEnvVars() {
  return [
    ...(!getSupabaseUrl() ? ['SUPABASE_URL'] : []),
    ...(!getServiceRoleKey() ? ['SERVICE_ROLE_KEY'] : []),
  ];
}

export function hasSupabaseAdminCredentials() {
  return getMissingSupabaseAdminEnvVars().length === 0;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = getSupabaseUrl();
  const SUPABASE_SERVICE_ROLE_KEY = getServiceRoleKey();

  const missing = getMissingSupabaseAdminEnvVars();
  if (missing.length > 0) {
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Add the missing value in project Secrets.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL!, SUPABASE_SERVICE_ROLE_KEY!, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@orizino/supabase/client-server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    const client = _supabaseAdmin ??= createSupabaseAdminClient();
    return Reflect.get(client, prop, receiver);
  },
});
// code:4ce0
