import { supabase } from "./supabase";

/**
 * Invoices are generated by the `generate-invoice` Supabase Edge Function —
 * the same one masterpanel could use — so this static SPA never needs its
 * own server or a secret Resend key. It returns ready-to-print HTML plus,
 * optionally, triggers the email send server-side.
 */
export async function generateInvoice(orderId: string, sendEmail = false, toOverride?: string) {
  const { data, error } = await supabase.functions.invoke("generate-invoice", {
    body: { order_id: orderId, send_email: sendEmail, to: toOverride },
  });
  if (error) throw new Error(error.message);
  return data as { ok: boolean; invoice_html: string; emailed?: boolean; emailError?: string };
}

/** Open the invoice HTML in a new tab and trigger the browser print dialog (Save as PDF works everywhere, including on Android/Capacitor's system print sheet). */
export function printInvoiceHtml(html: string) {
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.open();
  win.document.write(html);
  win.document.close();
  win.onload = () => win.print();
  // Some browsers fire onload before assets settle — a short fallback timer
  // covers that without relying on a fixed delay everywhere.
  setTimeout(() => { try { win.print(); } catch {} }, 400);
}
