import { supabase } from "./supabase";

/**
 * Invoices are generated by the `generate-invoice` Supabase Edge Function —
 * the same one masterpanel could use — so this static SPA never needs its
 * own server or a secret Resend key. It returns ready-to-print HTML plus,
 * optionally, triggers the email send server-side.
 */
export async function generateInvoice(orderId: string, sendEmail = false, toOverride?: string) {
  const { data, error } = await supabase.functions.invoke("generate-invoice", {
    body: { order_id: orderId, send_email: sendEmail, to: toOverride },
  });
  if (error) throw new Error(error.message);
  return data as { ok: boolean; invoice_html: string; emailed?: boolean; emailError?: string };
}

/** Open the invoice HTML in a new tab and trigger the browser print dialog (Save as PDF works everywhere, including on Android/Capacitor's system print sheet). */
export function printInvoiceHtml(html: string) {
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.open();
  win.document.write(html);
  win.document.close();
  win.onload = () => win.print();
  setTimeout(() => { try { win.print(); } catch {} }, 400);
}

export function printThermalSlipHtml(order: any, items: any[], brandName = "ORIZINO") {
  const dateStr = new Date(order.created_at || Date.now()).toLocaleString("en-US", {
    year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit"
  });
  const itemsHtml = (items || []).map((it: any) => `
    <tr>
      <td style="padding: 4px 0; font-weight: 600;">
        ${it.product_name || "Item"}
        ${it.sku ? `<br/><span style="font-size: 10px; color: #666;">SKU: ${it.sku}</span>` : ""}
      </td>
      <td style="padding: 4px 0; text-align: center;">${it.quantity ?? 1}</td>
      <td style="padding: 4px 0; text-align: right; font-family: monospace;">৳${Number(it.total_price || 0).toLocaleString()}</td>
    </tr>
  `).join("");

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8"/>
      <title>POS Receipt - ${order.order_number}</title>
      <style>
        @page { size: 80mm auto; margin: 4mm; }
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
          width: 72mm;
          margin: 0 auto;
          padding: 6px 0;
          color: #000;
          font-size: 12px;
          line-height: 1.4;
        }
        .header { text-align: center; margin-bottom: 10px; }
        .header h1 { font-size: 17px; font-weight: 900; margin: 0 0 4px; text-transform: uppercase; letter-spacing: 0.5px; }
        .header p { margin: 2px 0; font-size: 11px; color: #444; }
        .divider { border-top: 1px dashed #000; margin: 8px 0; }
        .info-row { display: flex; justify-content: space-between; font-size: 11px; margin: 2px 0; }
        table { width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 11px; }
        th { border-bottom: 1px solid #000; padding: 4px 0; text-align: left; font-size: 10px; text-transform: uppercase; }
        .total-row { display: flex; justify-content: space-between; font-size: 12px; font-weight: bold; margin: 4px 0; }
        .grand-total { font-size: 14px; font-weight: 900; border-top: 1px solid #000; border-bottom: 1px solid #000; padding: 6px 0; margin-top: 6px; }
        .badge { text-align: center; font-weight: bold; font-size: 11px; padding: 5px; border: 1px solid #000; margin: 10px 0 6px; text-transform: uppercase; letter-spacing: 0.5px; }
        .footer { text-align: center; font-size: 10px; color: #555; margin-top: 10px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${brandName}</h1>
      </div>
      <div class="divider"></div>
      <div class="info-row"><span>Receipt #:</span><strong>${order.order_number}</strong></div>
      <div class="info-row"><span>Date:</span><span>${dateStr}</span></div>
      <div class="info-row"><span>Customer:</span><strong>${order.customer_name || order.shipping_address?.full_name || "Walk-in Customer"}</strong></div>
      ${order.guest_phone || order.shipping_address?.phone ? `<div class="info-row"><span>Phone:</span><span>${order.guest_phone || order.shipping_address?.phone}</span></div>` : ""}
      <div class="info-row"><span>Channel:</span><span>${String(order.order_source || "Store Counter").toUpperCase()}</span></div>
      <div class="divider"></div>
      <table>
        <thead>
          <tr>
            <th>Item</th>
            <th style="text-align: center;">Qty</th>
            <th style="text-align: right;">Total</th>
          </tr>
        </thead>
        <tbody>
          ${itemsHtml}
        </tbody>
      </table>
      <div class="divider"></div>
      <div class="info-row"><span>Subtotal:</span><span>৳${Number(order.subtotal || 0).toLocaleString()}</span></div>
      ${order.shipping_fee ? `<div class="info-row"><span>Shipping:</span><span>৳${Number(order.shipping_fee).toLocaleString()}</span></div>` : ""}
      ${order.coupon_discount ? `<div class="info-row"><span>Discount:</span><span>-৳${Number(order.coupon_discount).toLocaleString()}</span></div>` : ""}
      <div class="total-row grand-total">
        <span>TOTAL PAID:</span>
        <span>৳${Number(order.total || 0).toLocaleString()}</span>
      </div>
      <div class="badge">
        ${order.status === "delivered" ? "PAID IN FULL · DELIVERED" : "PAID IN FULL"}
      </div>
      <div class="footer">
        <p>Thank you for shopping with ${brandName}!</p>
        <p>Keep this receipt slip for warranty & authentication.</p>
      </div>
      <script>
        window.onload = function() {
          window.print();
        };
      </script>
    </body>
    </html>
  `;

  const printWin = window.open("", "_blank", "width=420,height=650");
  if (printWin) {
    printWin.document.open();
    printWin.document.write(html);
    printWin.document.close();
  }
}
