import { z } from "zod";

export const InvoiceSettingsSchema = z.object({
  preset: z.enum(["cherry_vanilla", "classic", "modern", "minimal", "bold", "custom"]).default("cherry_vanilla"),
  accent_color: z.string().regex(/^#[0-9a-fA-F]{6}$/).default("#6B0F1A"),
  text_color: z.string().regex(/^#[0-9a-fA-F]{6}$/).default("#1D070B"),
  muted_color: z.string().regex(/^#[0-9a-fA-F]{6}$/).default("#785860"),
  bg_color: z.string().regex(/^#[0-9a-fA-F]{6}$/).default("#FDFBF7"),
  font_family: z.string().max(80).default("Plus Jakarta Sans"),
  heading_font_family: z.string().max(80).default("Playfair Display"),
  font_size: z.number().int().min(8).max(24).default(15),
  show_logo: z.boolean().default(true),
  show_brand_mark: z.boolean().default(true),
  show_invoice_number: z.boolean().default(true),
  show_order_number: z.boolean().default(true),
  show_issue_date: z.boolean().default(true),
  show_due_date: z.boolean().default(false),
  show_billing_address: z.boolean().default(true),
  show_shipping_address: z.boolean().default(true),
  show_customer_email: z.boolean().default(true),
  show_customer_phone: z.boolean().default(true),
  show_item_sku: z.boolean().default(true),
  show_item_image: z.boolean().default(false),
  show_subtotal: z.boolean().default(true),
  show_shipping_fee: z.boolean().default(true),
  show_tax: z.boolean().default(false),
  show_discount: z.boolean().default(true),
  show_total: z.boolean().default(true),
  show_payment_method: z.boolean().default(true),
  show_tracking_number: z.boolean().default(true),
  show_notes: z.boolean().default(true),
  show_footer: z.boolean().default(true),
  show_watermark: z.boolean().default(true),
  watermark_opacity: z.number().min(0.01).max(0.5).default(0.08),
  watermark_url: z.string().default(""),
  header_text: z.string().max(400).default(""),
  footer_text: z.string().max(800).default("Thank you for your order."),
  notes_text: z.string().max(2000).default(""),
  terms_text: z.string().max(4000).default("All Orizino pieces include digital authenticity verification. Please scan the QR code to view your verified order details."),
  advanced_mode: z.boolean().default(false),
  advanced_html: z.string().max(60000).default(""),

  // ── Sizing & Alignment Customization ──
  qr_size: z.enum(["compact", "medium", "large", "full_width"]).default("full_width"),
  qr_scale: z.number().min(50).max(200).default(100),
  logo_size: z.enum(["small", "medium", "large", "extra_large"]).default("large"),
  logo_scale: z.number().min(50).max(200).default(100),
  brand_name_size: z.enum(["small", "medium", "large", "extra_large"]).default("large"),
  brand_name_scale: z.number().min(50).max(200).default(100),
  customer_info_size: z.enum(["compact", "normal", "large", "extra_large"]).default("normal"),
  customer_info_scale: z.number().min(60).max(180).default(100),
  customer_info_align: z.enum(["left", "center", "right"]).default("left"),
});

export type InvoiceSettings = z.infer<typeof InvoiceSettingsSchema>;
