/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MainRouteImport } from './routes/_main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainWishlistRouteImport } from './routes/_main.wishlist'
import { Route as MainSupportRouteImport } from './routes/_main.support'
import { Route as MainShopRouteImport } from './routes/_main.shop'
import { Route as MainSettingsRouteImport } from './routes/_main.settings'
import { Route as MainResetPasswordRouteImport } from './routes/_main.reset-password'
import { Route as MainProfileRouteImport } from './routes/_main.profile'
import { Route as MainOfflineRouteImport } from './routes/_main.offline'
import { Route as MainInventoryRouteImport } from './routes/_main.inventory'
import { Route as MainHomeRouteImport } from './routes/_main.home'
import { Route as MainCheckoutGuestRouteImport } from './routes/_main.checkout-guest'
import { Route as MainCheckoutRouteImport } from './routes/_main.checkout'
import { Route as MainCartRouteImport } from './routes/_main.cart'
import { Route as MainAuthRouteImport } from './routes/_main.auth'
import { Route as MainAffiliateRouteImport } from './routes/_main.affiliate'
import { Route as MainPrivacyRouteImport } from './routes/_main.privacy'
import { Route as MainTermsRouteImport } from './routes/_main.terms'
import { Route as MainRefundRouteImport } from './routes/_main.refund'
import { Route as MainCookiesRouteImport } from './routes/_main.cookies'
import { Route as MainVerifyIndexRouteImport } from './routes/_main.verify.index'
import { Route as MainOrdersIndexRouteImport } from './routes/_main.orders/index'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api.public.unsubscribe'
import { Route as MainVerifyCodeRouteImport } from './routes/_main.verify.$code'
import { Route as MainProductSlugRouteImport } from './routes/_main.product.$slug'
import { Route as MainPageSlugRouteImport } from './routes/_main.page.$slug'
import { Route as MainCategoriesSlugRouteImport } from './routes/_main.categories.$slug'
import { Route as ApiPublicHooksSyncAllShipmentsRouteImport } from './routes/api.public.hooks.sync-all-shipments'
import { Route as ApiPublicHooksStripeWebhookRouteImport } from './routes/api.public.hooks.stripe-webhook'
import { Route as ApiPublicHooksResendWebhookRouteImport } from './routes/api.public.hooks.resend-webhook'
import { Route as ApiPublicHooksProcessEmailAutomationsRouteImport } from './routes/api.public.hooks.process-email-automations'
import { Route as ApiPublicHooksDispatchEmailCampaignsRouteImport } from './routes/api.public.hooks.dispatch-email-campaigns'
import { Route as ApiPublicHooksAffiliateReportWeeklyRouteImport } from './routes/api.public.hooks.affiliate-report-weekly'
import { Route as ApiPublicHooksAffiliateReportMonthlyRouteImport } from './routes/api.public.hooks.affiliate-report-monthly'
import { Route as MainOrdersIdTrackRouteImport } from './routes/_main.orders/$id.track'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainWishlistRoute = MainWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => MainRoute,
} as any)
const MainSupportRoute = MainSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MainRoute,
} as any)
const MainShopRoute = MainShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainResetPasswordRoute = MainResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainOfflineRoute = MainOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => MainRoute,
} as any)
const MainInventoryRoute = MainInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => MainRoute,
} as any)
const MainHomeRoute = MainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainRoute,
} as any)
const MainCheckoutGuestRoute = MainCheckoutGuestRouteImport.update({
  id: '/checkout-guest',
  path: '/checkout-guest',
  getParentRoute: () => MainRoute,
} as any)
const MainCheckoutRoute = MainCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MainRoute,
} as any)
const MainCartRoute = MainCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MainRoute,
} as any)
const MainAuthRoute = MainAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => MainRoute,
} as any)
const MainAffiliateRoute = MainAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => MainRoute,
} as any)
const MainPrivacyRoute = MainPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MainRoute,
} as any)
const MainTermsRoute = MainTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MainRoute,
} as any)
const MainRefundRoute = MainRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => MainRoute,
} as any)
const MainCookiesRoute = MainCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => MainRoute,
} as any)
const MainVerifyIndexRoute = MainVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => MainRoute,
} as any)
const MainOrdersIndexRoute = MainOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => MainRoute,
} as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const MainVerifyCodeRoute = MainVerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => MainRoute,
} as any)
const MainProductSlugRoute = MainProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => MainRoute,
} as any)
const MainPageSlugRoute = MainPageSlugRouteImport.update({
  id: '/page/$slug',
  path: '/page/$slug',
  getParentRoute: () => MainRoute,
} as any)
const MainCategoriesSlugRoute = MainCategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => MainRoute,
} as any)
const ApiPublicHooksSyncAllShipmentsRoute =
  ApiPublicHooksSyncAllShipmentsRouteImport.update({
    id: '/api/public/hooks/sync-all-shipments',
    path: '/api/public/hooks/sync-all-shipments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStripeWebhookRoute =
  ApiPublicHooksStripeWebhookRouteImport.update({
    id: '/api/public/hooks/stripe-webhook',
    path: '/api/public/hooks/stripe-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResendWebhookRoute =
  ApiPublicHooksResendWebhookRouteImport.update({
    id: '/api/public/hooks/resend-webhook',
    path: '/api/public/hooks/resend-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessEmailAutomationsRoute =
  ApiPublicHooksProcessEmailAutomationsRouteImport.update({
    id: '/api/public/hooks/process-email-automations',
    path: '/api/public/hooks/process-email-automations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchEmailCampaignsRoute =
  ApiPublicHooksDispatchEmailCampaignsRouteImport.update({
    id: '/api/public/hooks/dispatch-email-campaigns',
    path: '/api/public/hooks/dispatch-email-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAffiliateReportWeeklyRoute =
  ApiPublicHooksAffiliateReportWeeklyRouteImport.update({
    id: '/api/public/hooks/affiliate-report-weekly',
    path: '/api/public/hooks/affiliate-report-weekly',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAffiliateReportMonthlyRoute =
  ApiPublicHooksAffiliateReportMonthlyRouteImport.update({
    id: '/api/public/hooks/affiliate-report-monthly',
    path: '/api/public/hooks/affiliate-report-monthly',
    getParentRoute: () => rootRouteImport,
  } as any)
const MainOrdersIdTrackRoute = MainOrdersIdTrackRouteImport.update({
  id: '/orders/$id/track',
  path: '/orders/$id/track',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/affiliate': typeof MainAffiliateRoute
  '/auth': typeof MainAuthRoute
  '/cart': typeof MainCartRoute
  '/checkout': typeof MainCheckoutRoute
  '/checkout-guest': typeof MainCheckoutGuestRoute
  '/home': typeof MainHomeRoute
  '/inventory': typeof MainInventoryRoute
  '/offline': typeof MainOfflineRoute
  '/profile': typeof MainProfileRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/settings': typeof MainSettingsRoute
  '/shop': typeof MainShopRoute
  '/support': typeof MainSupportRoute
  '/wishlist': typeof MainWishlistRoute
  '/categories/$slug': typeof MainCategoriesSlugRoute
  '/page/$slug': typeof MainPageSlugRoute
  '/product/$slug': typeof MainProductSlugRoute
  '/verify/$code': typeof MainVerifyCodeRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/orders/': typeof MainOrdersIndexRoute
  '/verify/': typeof MainVerifyIndexRoute
  '/orders/$id/track': typeof MainOrdersIdTrackRoute
  '/api/public/hooks/affiliate-report-monthly': typeof ApiPublicHooksAffiliateReportMonthlyRoute
  '/api/public/hooks/affiliate-report-weekly': typeof ApiPublicHooksAffiliateReportWeeklyRoute
  '/api/public/hooks/dispatch-email-campaigns': typeof ApiPublicHooksDispatchEmailCampaignsRoute
  '/api/public/hooks/process-email-automations': typeof ApiPublicHooksProcessEmailAutomationsRoute
  '/api/public/hooks/resend-webhook': typeof ApiPublicHooksResendWebhookRoute
  '/api/public/hooks/stripe-webhook': typeof ApiPublicHooksStripeWebhookRoute
  '/api/public/hooks/sync-all-shipments': typeof ApiPublicHooksSyncAllShipmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/affiliate': typeof MainAffiliateRoute
  '/auth': typeof MainAuthRoute
  '/cart': typeof MainCartRoute
  '/checkout': typeof MainCheckoutRoute
  '/checkout-guest': typeof MainCheckoutGuestRoute
  '/home': typeof MainHomeRoute
  '/inventory': typeof MainInventoryRoute
  '/offline': typeof MainOfflineRoute
  '/profile': typeof MainProfileRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/settings': typeof MainSettingsRoute
  '/shop': typeof MainShopRoute
  '/support': typeof MainSupportRoute
  '/wishlist': typeof MainWishlistRoute
  '/categories/$slug': typeof MainCategoriesSlugRoute
  '/page/$slug': typeof MainPageSlugRoute
  '/product/$slug': typeof MainProductSlugRoute
  '/verify/$code': typeof MainVerifyCodeRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/orders': typeof MainOrdersIndexRoute
  '/verify': typeof MainVerifyIndexRoute
  '/orders/$id/track': typeof MainOrdersIdTrackRoute
  '/api/public/hooks/affiliate-report-monthly': typeof ApiPublicHooksAffiliateReportMonthlyRoute
  '/api/public/hooks/affiliate-report-weekly': typeof ApiPublicHooksAffiliateReportWeeklyRoute
  '/api/public/hooks/dispatch-email-campaigns': typeof ApiPublicHooksDispatchEmailCampaignsRoute
  '/api/public/hooks/process-email-automations': typeof ApiPublicHooksProcessEmailAutomationsRoute
  '/api/public/hooks/resend-webhook': typeof ApiPublicHooksResendWebhookRoute
  '/api/public/hooks/stripe-webhook': typeof ApiPublicHooksStripeWebhookRoute
  '/api/public/hooks/sync-all-shipments': typeof ApiPublicHooksSyncAllShipmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_main/affiliate': typeof MainAffiliateRoute
  '/_main/auth': typeof MainAuthRoute
  '/_main/cart': typeof MainCartRoute
  '/_main/checkout': typeof MainCheckoutRoute
  '/_main/checkout-guest': typeof MainCheckoutGuestRoute
  '/_main/home': typeof MainHomeRoute
  '/_main/inventory': typeof MainInventoryRoute
  '/_main/offline': typeof MainOfflineRoute
  '/_main/profile': typeof MainProfileRoute
  '/_main/reset-password': typeof MainResetPasswordRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/shop': typeof MainShopRoute
  '/_main/support': typeof MainSupportRoute
  '/_main/wishlist': typeof MainWishlistRoute
  '/_main/categories/$slug': typeof MainCategoriesSlugRoute
  '/_main/page/$slug': typeof MainPageSlugRoute
  '/_main/product/$slug': typeof MainProductSlugRoute
  '/_main/verify/$code': typeof MainVerifyCodeRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/_main/orders/': typeof MainOrdersIndexRoute
  '/_main/verify/': typeof MainVerifyIndexRoute
  '/_main/orders/$id/track': typeof MainOrdersIdTrackRoute
  '/api/public/hooks/affiliate-report-monthly': typeof ApiPublicHooksAffiliateReportMonthlyRoute
  '/api/public/hooks/affiliate-report-weekly': typeof ApiPublicHooksAffiliateReportWeeklyRoute
  '/api/public/hooks/dispatch-email-campaigns': typeof ApiPublicHooksDispatchEmailCampaignsRoute
  '/api/public/hooks/process-email-automations': typeof ApiPublicHooksProcessEmailAutomationsRoute
  '/api/public/hooks/resend-webhook': typeof ApiPublicHooksResendWebhookRoute
  '/api/public/hooks/stripe-webhook': typeof ApiPublicHooksStripeWebhookRoute
  '/api/public/hooks/sync-all-shipments': typeof ApiPublicHooksSyncAllShipmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/affiliate'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/checkout-guest'
    | '/home'
    | '/inventory'
    | '/offline'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/shop'
    | '/support'
    | '/wishlist'
    | '/categories/$slug'
    | '/page/$slug'
    | '/product/$slug'
    | '/verify/$code'
    | '/api/public/unsubscribe'
    | '/orders/'
    | '/verify/'
    | '/orders/$id/track'
    | '/api/public/hooks/affiliate-report-monthly'
    | '/api/public/hooks/affiliate-report-weekly'
    | '/api/public/hooks/dispatch-email-campaigns'
    | '/api/public/hooks/process-email-automations'
    | '/api/public/hooks/resend-webhook'
    | '/api/public/hooks/stripe-webhook'
    | '/api/public/hooks/sync-all-shipments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/affiliate'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/checkout-guest'
    | '/home'
    | '/inventory'
    | '/offline'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/shop'
    | '/support'
    | '/wishlist'
    | '/categories/$slug'
    | '/page/$slug'
    | '/product/$slug'
    | '/verify/$code'
    | '/api/public/unsubscribe'
    | '/orders'
    | '/verify'
    | '/orders/$id/track'
    | '/api/public/hooks/affiliate-report-monthly'
    | '/api/public/hooks/affiliate-report-weekly'
    | '/api/public/hooks/dispatch-email-campaigns'
    | '/api/public/hooks/process-email-automations'
    | '/api/public/hooks/resend-webhook'
    | '/api/public/hooks/stripe-webhook'
    | '/api/public/hooks/sync-all-shipments'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/sitemap.xml'
    | '/_main/affiliate'
    | '/_main/auth'
    | '/_main/cart'
    | '/_main/checkout'
    | '/_main/checkout-guest'
    | '/_main/home'
    | '/_main/inventory'
    | '/_main/offline'
    | '/_main/profile'
    | '/_main/reset-password'
    | '/_main/settings'
    | '/_main/shop'
    | '/_main/support'
    | '/_main/wishlist'
    | '/_main/categories/$slug'
    | '/_main/page/$slug'
    | '/_main/product/$slug'
    | '/_main/verify/$code'
    | '/api/public/unsubscribe'
    | '/_main/orders/'
    | '/_main/verify/'
    | '/_main/orders/$id/track'
    | '/api/public/hooks/affiliate-report-monthly'
    | '/api/public/hooks/affiliate-report-weekly'
    | '/api/public/hooks/dispatch-email-campaigns'
    | '/api/public/hooks/process-email-automations'
    | '/api/public/hooks/resend-webhook'
    | '/api/public/hooks/stripe-webhook'
    | '/api/public/hooks/sync-all-shipments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
  ApiPublicHooksAffiliateReportMonthlyRoute: typeof ApiPublicHooksAffiliateReportMonthlyRoute
  ApiPublicHooksAffiliateReportWeeklyRoute: typeof ApiPublicHooksAffiliateReportWeeklyRoute
  ApiPublicHooksDispatchEmailCampaignsRoute: typeof ApiPublicHooksDispatchEmailCampaignsRoute
  ApiPublicHooksProcessEmailAutomationsRoute: typeof ApiPublicHooksProcessEmailAutomationsRoute
  ApiPublicHooksResendWebhookRoute: typeof ApiPublicHooksResendWebhookRoute
  ApiPublicHooksStripeWebhookRoute: typeof ApiPublicHooksStripeWebhookRoute
  ApiPublicHooksSyncAllShipmentsRoute: typeof ApiPublicHooksSyncAllShipmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/wishlist': {
      id: '/_main/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof MainWishlistRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/support': {
      id: '/_main/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof MainSupportRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/shop': {
      id: '/_main/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof MainShopRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/reset-password': {
      id: '/_main/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof MainResetPasswordRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/offline': {
      id: '/_main/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof MainOfflineRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/inventory': {
      id: '/_main/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof MainInventoryRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/home': {
      id: '/_main/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainHomeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/checkout-guest': {
      id: '/_main/checkout-guest'
      path: '/checkout-guest'
      fullPath: '/checkout-guest'
      preLoaderRoute: typeof MainCheckoutGuestRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/checkout': {
      id: '/_main/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof MainCheckoutRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/cart': {
      id: '/_main/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof MainCartRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/auth': {
      id: '/_main/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof MainAuthRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/affiliate': {
      id: '/_main/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof MainAffiliateRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/verify/': {
      id: '/_main/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof MainVerifyIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/orders/': {
      id: '/_main/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof MainOrdersIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/verify/$code': {
      id: '/_main/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof MainVerifyCodeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/product/$slug': {
      id: '/_main/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof MainProductSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/page/$slug': {
      id: '/_main/page/$slug'
      path: '/page/$slug'
      fullPath: '/page/$slug'
      preLoaderRoute: typeof MainPageSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/categories/$slug': {
      id: '/_main/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof MainCategoriesSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/public/hooks/sync-all-shipments': {
      id: '/api/public/hooks/sync-all-shipments'
      path: '/api/public/hooks/sync-all-shipments'
      fullPath: '/api/public/hooks/sync-all-shipments'
      preLoaderRoute: typeof ApiPublicHooksSyncAllShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stripe-webhook': {
      id: '/api/public/hooks/stripe-webhook'
      path: '/api/public/hooks/stripe-webhook'
      fullPath: '/api/public/hooks/stripe-webhook'
      preLoaderRoute: typeof ApiPublicHooksStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resend-webhook': {
      id: '/api/public/hooks/resend-webhook'
      path: '/api/public/hooks/resend-webhook'
      fullPath: '/api/public/hooks/resend-webhook'
      preLoaderRoute: typeof ApiPublicHooksResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-email-automations': {
      id: '/api/public/hooks/process-email-automations'
      path: '/api/public/hooks/process-email-automations'
      fullPath: '/api/public/hooks/process-email-automations'
      preLoaderRoute: typeof ApiPublicHooksProcessEmailAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-email-campaigns': {
      id: '/api/public/hooks/dispatch-email-campaigns'
      path: '/api/public/hooks/dispatch-email-campaigns'
      fullPath: '/api/public/hooks/dispatch-email-campaigns'
      preLoaderRoute: typeof ApiPublicHooksDispatchEmailCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/affiliate-report-weekly': {
      id: '/api/public/hooks/affiliate-report-weekly'
      path: '/api/public/hooks/affiliate-report-weekly'
      fullPath: '/api/public/hooks/affiliate-report-weekly'
      preLoaderRoute: typeof ApiPublicHooksAffiliateReportWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/affiliate-report-monthly': {
      id: '/api/public/hooks/affiliate-report-monthly'
      path: '/api/public/hooks/affiliate-report-monthly'
      fullPath: '/api/public/hooks/affiliate-report-monthly'
      preLoaderRoute: typeof ApiPublicHooksAffiliateReportMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/orders/$id/track': {
      id: '/_main/orders/$id/track'
      path: '/orders/$id/track'
      fullPath: '/orders/$id/track'
      preLoaderRoute: typeof MainOrdersIdTrackRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainAffiliateRoute: typeof MainAffiliateRoute
  MainPrivacyRoute: typeof MainPrivacyRoute
  MainTermsRoute: typeof MainTermsRoute
  MainRefundRoute: typeof MainRefundRoute
  MainCookiesRoute: typeof MainCookiesRoute
  MainAuthRoute: typeof MainAuthRoute
  MainCartRoute: typeof MainCartRoute
  MainCheckoutRoute: typeof MainCheckoutRoute
  MainCheckoutGuestRoute: typeof MainCheckoutGuestRoute
  MainHomeRoute: typeof MainHomeRoute
  MainInventoryRoute: typeof MainInventoryRoute
  MainOfflineRoute: typeof MainOfflineRoute
  MainProfileRoute: typeof MainProfileRoute
  MainResetPasswordRoute: typeof MainResetPasswordRoute
  MainSettingsRoute: typeof MainSettingsRoute
  MainShopRoute: typeof MainShopRoute
  MainSupportRoute: typeof MainSupportRoute
  MainWishlistRoute: typeof MainWishlistRoute
  MainCategoriesSlugRoute: typeof MainCategoriesSlugRoute
  MainPageSlugRoute: typeof MainPageSlugRoute
  MainProductSlugRoute: typeof MainProductSlugRoute
  MainVerifyCodeRoute: typeof MainVerifyCodeRoute
  MainOrdersIndexRoute: typeof MainOrdersIndexRoute
  MainVerifyIndexRoute: typeof MainVerifyIndexRoute
  MainOrdersIdTrackRoute: typeof MainOrdersIdTrackRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAffiliateRoute: MainAffiliateRoute,
  MainPrivacyRoute: MainPrivacyRoute,
  MainTermsRoute: MainTermsRoute,
  MainRefundRoute: MainRefundRoute,
  MainCookiesRoute: MainCookiesRoute,
  MainAuthRoute: MainAuthRoute,
  MainCartRoute: MainCartRoute,
  MainCheckoutRoute: MainCheckoutRoute,
  MainCheckoutGuestRoute: MainCheckoutGuestRoute,
  MainHomeRoute: MainHomeRoute,
  MainInventoryRoute: MainInventoryRoute,
  MainOfflineRoute: MainOfflineRoute,
  MainProfileRoute: MainProfileRoute,
  MainResetPasswordRoute: MainResetPasswordRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainShopRoute: MainShopRoute,
  MainSupportRoute: MainSupportRoute,
  MainWishlistRoute: MainWishlistRoute,
  MainCategoriesSlugRoute: MainCategoriesSlugRoute,
  MainPageSlugRoute: MainPageSlugRoute,
  MainProductSlugRoute: MainProductSlugRoute,
  MainVerifyCodeRoute: MainVerifyCodeRoute,
  MainOrdersIndexRoute: MainOrdersIndexRoute,
  MainVerifyIndexRoute: MainVerifyIndexRoute,
  MainOrdersIdTrackRoute: MainOrdersIdTrackRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
  ApiPublicHooksAffiliateReportMonthlyRoute:
    ApiPublicHooksAffiliateReportMonthlyRoute,
  ApiPublicHooksAffiliateReportWeeklyRoute:
    ApiPublicHooksAffiliateReportWeeklyRoute,
  ApiPublicHooksDispatchEmailCampaignsRoute:
    ApiPublicHooksDispatchEmailCampaignsRoute,
  ApiPublicHooksProcessEmailAutomationsRoute:
    ApiPublicHooksProcessEmailAutomationsRoute,
  ApiPublicHooksResendWebhookRoute: ApiPublicHooksResendWebhookRoute,
  ApiPublicHooksStripeWebhookRoute: ApiPublicHooksStripeWebhookRoute,
  ApiPublicHooksSyncAllShipmentsRoute: ApiPublicHooksSyncAllShipmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
